// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.18.1
// source: api/protobuf/juso/juso.proto

package regcode

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Regcode struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *Regcode) Reset() {
	*x = Regcode{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_protobuf_juso_juso_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Regcode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Regcode) ProtoMessage() {}

func (x *Regcode) ProtoReflect() protoreflect.Message {
	mi := &file_api_protobuf_juso_juso_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Regcode.ProtoReflect.Descriptor instead.
func (*Regcode) Descriptor() ([]byte, []int) {
	return file_api_protobuf_juso_juso_proto_rawDescGZIP(), []int{0}
}

func (x *Regcode) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Regcode) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ListRegcodesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RegcodePattern string `protobuf:"bytes,1,opt,name=regcode_pattern,json=regcodePattern,proto3" json:"regcode_pattern,omitempty"`
	IsIgnoreZero   bool   `protobuf:"varint,2,opt,name=is_ignore_zero,json=isIgnoreZero,proto3" json:"is_ignore_zero,omitempty"` // regcode_pattern값이 "1111*"일 경우 "1111000000" 코드는 제외된다.
}

func (x *ListRegcodesRequest) Reset() {
	*x = ListRegcodesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_protobuf_juso_juso_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListRegcodesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRegcodesRequest) ProtoMessage() {}

func (x *ListRegcodesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_protobuf_juso_juso_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRegcodesRequest.ProtoReflect.Descriptor instead.
func (*ListRegcodesRequest) Descriptor() ([]byte, []int) {
	return file_api_protobuf_juso_juso_proto_rawDescGZIP(), []int{1}
}

func (x *ListRegcodesRequest) GetRegcodePattern() string {
	if x != nil {
		return x.RegcodePattern
	}
	return ""
}

func (x *ListRegcodesRequest) GetIsIgnoreZero() bool {
	if x != nil {
		return x.IsIgnoreZero
	}
	return false
}

type ListRegcodesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Regcodes []*Regcode `protobuf:"bytes,1,rep,name=regcodes,proto3" json:"regcodes,omitempty"`
}

func (x *ListRegcodesResponse) Reset() {
	*x = ListRegcodesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_protobuf_juso_juso_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListRegcodesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRegcodesResponse) ProtoMessage() {}

func (x *ListRegcodesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_protobuf_juso_juso_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRegcodesResponse.ProtoReflect.Descriptor instead.
func (*ListRegcodesResponse) Descriptor() ([]byte, []int) {
	return file_api_protobuf_juso_juso_proto_rawDescGZIP(), []int{2}
}

func (x *ListRegcodesResponse) GetRegcodes() []*Regcode {
	if x != nil {
		return x.Regcodes
	}
	return nil
}

var File_api_protobuf_juso_juso_proto protoreflect.FileDescriptor

var file_api_protobuf_juso_juso_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x6a,
	0x75, 0x73, 0x6f, 0x2f, 0x6a, 0x75, 0x73, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c,
	0x6a, 0x75, 0x73, 0x6f, 0x2e, 0x72, 0x65, 0x67, 0x63, 0x6f, 0x64, 0x65, 0x1a, 0x1c, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x31, 0x0a, 0x07, 0x52, 0x65,
	0x67, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x64, 0x0a,
	0x13, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x67, 0x63, 0x6f, 0x64, 0x65, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x27, 0x0a, 0x0f, 0x72, 0x65, 0x67, 0x63, 0x6f, 0x64, 0x65, 0x5f,
	0x70, 0x61, 0x74, 0x74, 0x65, 0x72, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x72,
	0x65, 0x67, 0x63, 0x6f, 0x64, 0x65, 0x50, 0x61, 0x74, 0x74, 0x65, 0x72, 0x6e, 0x12, 0x24, 0x0a,
	0x0e, 0x69, 0x73, 0x5f, 0x69, 0x67, 0x6e, 0x6f, 0x72, 0x65, 0x5f, 0x7a, 0x65, 0x72, 0x6f, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0c, 0x69, 0x73, 0x49, 0x67, 0x6e, 0x6f, 0x72, 0x65, 0x5a,
	0x65, 0x72, 0x6f, 0x22, 0x49, 0x0a, 0x14, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x67, 0x63, 0x6f,
	0x64, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x31, 0x0a, 0x08, 0x72,
	0x65, 0x67, 0x63, 0x6f, 0x64, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e,
	0x6a, 0x75, 0x73, 0x6f, 0x2e, 0x72, 0x65, 0x67, 0x63, 0x6f, 0x64, 0x65, 0x2e, 0x52, 0x65, 0x67,
	0x63, 0x6f, 0x64, 0x65, 0x52, 0x08, 0x72, 0x65, 0x67, 0x63, 0x6f, 0x64, 0x65, 0x73, 0x32, 0x7d,
	0x0a, 0x0e, 0x52, 0x65, 0x67, 0x63, 0x6f, 0x64, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x6b, 0x0a, 0x0c, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x67, 0x63, 0x6f, 0x64, 0x65, 0x73,
	0x12, 0x21, 0x2e, 0x6a, 0x75, 0x73, 0x6f, 0x2e, 0x72, 0x65, 0x67, 0x63, 0x6f, 0x64, 0x65, 0x2e,
	0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x67, 0x63, 0x6f, 0x64, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x6a, 0x75, 0x73, 0x6f, 0x2e, 0x72, 0x65, 0x67, 0x63, 0x6f,
	0x64, 0x65, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x67, 0x63, 0x6f, 0x64, 0x65, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x14, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x0e, 0x12,
	0x0c, 0x2f, 0x76, 0x31, 0x2f, 0x72, 0x65, 0x67, 0x63, 0x6f, 0x64, 0x65, 0x73, 0x42, 0x0e, 0x5a,
	0x0c, 0x6a, 0x75, 0x73, 0x6f, 0x2f, 0x72, 0x65, 0x67, 0x63, 0x6f, 0x64, 0x65, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_protobuf_juso_juso_proto_rawDescOnce sync.Once
	file_api_protobuf_juso_juso_proto_rawDescData = file_api_protobuf_juso_juso_proto_rawDesc
)

func file_api_protobuf_juso_juso_proto_rawDescGZIP() []byte {
	file_api_protobuf_juso_juso_proto_rawDescOnce.Do(func() {
		file_api_protobuf_juso_juso_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_protobuf_juso_juso_proto_rawDescData)
	})
	return file_api_protobuf_juso_juso_proto_rawDescData
}

var file_api_protobuf_juso_juso_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_protobuf_juso_juso_proto_goTypes = []interface{}{
	(*Regcode)(nil),              // 0: juso.regcode.Regcode
	(*ListRegcodesRequest)(nil),  // 1: juso.regcode.ListRegcodesRequest
	(*ListRegcodesResponse)(nil), // 2: juso.regcode.ListRegcodesResponse
}
var file_api_protobuf_juso_juso_proto_depIdxs = []int32{
	0, // 0: juso.regcode.ListRegcodesResponse.regcodes:type_name -> juso.regcode.Regcode
	1, // 1: juso.regcode.RegcodeService.ListRegcodes:input_type -> juso.regcode.ListRegcodesRequest
	2, // 2: juso.regcode.RegcodeService.ListRegcodes:output_type -> juso.regcode.ListRegcodesResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_protobuf_juso_juso_proto_init() }
func file_api_protobuf_juso_juso_proto_init() {
	if File_api_protobuf_juso_juso_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_protobuf_juso_juso_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Regcode); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_protobuf_juso_juso_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListRegcodesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_protobuf_juso_juso_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListRegcodesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_protobuf_juso_juso_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_protobuf_juso_juso_proto_goTypes,
		DependencyIndexes: file_api_protobuf_juso_juso_proto_depIdxs,
		MessageInfos:      file_api_protobuf_juso_juso_proto_msgTypes,
	}.Build()
	File_api_protobuf_juso_juso_proto = out.File
	file_api_protobuf_juso_juso_proto_rawDesc = nil
	file_api_protobuf_juso_juso_proto_goTypes = nil
	file_api_protobuf_juso_juso_proto_depIdxs = nil
}
